package dclient;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Properties;

import org.apache.commons.lang3.RandomStringUtils;

public class KeyEncrypt {
	private final int DEFAULT_PASSWORD_LENGHT = 64;
	private final String DEFAULT_ENV_VARIABLE = "DCLIENT";

	private int passwordLenght;
	private String installationFolder;

	Key key;

	private String userPassword;
	private String sshFileName;
	private String sshNameIdentifier;
	private String sshPassword;
	private String envName;
	private String envPassword;

	Properties config;

	public static void main(String[] args) {
		KeyEncrypt keyEncrypt = new KeyEncrypt();
		keyEncrypt.loadInitProperties();
		keyEncrypt.userInput();
		keyEncrypt.setEnvVar();
		keyEncrypt.initKey();
	}

	private void loadInitProperties() {
		config = new Properties();
		try {
			config.load(new FileInputStream("./installConfig.properties"));
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		passwordLenght = Integer
				.parseInt(config.getProperty("password.lenght", Integer.toString(DEFAULT_PASSWORD_LENGHT)));
		installationFolder = config.getProperty("installation.folder", System.getProperty("user.home") + "/.dclient/");
		sshFileName = config.getProperty("ssh.keyname", "id_dclient.rsa");
		sshNameIdentifier = config.getProperty("ssh.identifier", System.getProperty("user.name"));
		envName = config.getProperty("env.variable", DEFAULT_ENV_VARIABLE);
	}

	private void userInput() {
		InputStreamReader isr = new InputStreamReader(System.in);
		BufferedReader br = new BufferedReader(isr);

		try {
			System.out.print("Inserisci la password => ");
			userPassword = br.readLine();

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private void initKey() {
		key = new Key(userPassword, envPassword);
	}

	private void setEnvVar() {
		envPassword = passwordGenerator();
		try {
			Runtime.getRuntime().exec("setx " + envName + " " + envPassword);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
	}

	private void setSSH() {
		sshPassword = passwordGenerator();
		try {
			Runtime.getRuntime().exec("ssh-keygen -f " + installationFolder + "/" + sshFileName + " -t rsa  -b 4096 -C "
					+ sshNameIdentifier + " -N " + sshPassword);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
	}

	private void movePublicKey() {

	}

	private String passwordGenerator() {
		return RandomStringUtils.randomAlphanumeric(passwordLenght);
	}

	private void createPropertiesFile() {
		Properties installProperties = new Properties();

		String[] openProperties = { "rsppTable.daysAdvance" };
		for (int i = 0; i < openProperties.length; i++) {
			installProperties.setProperty(openProperties[i], config.getProperty(openProperties[i]));
		}

		String[] encryptableProperties = { "ciao" };
		for (int i = 0; i < encryptableProperties.length; i++) {
			installProperties.setProperty(encryptableProperties[i],
					"ENC(" + key.getEnc().encrypt(config.getProperty(encryptableProperties[i])) + ")");
		}

		File file = new File(installationFolder + "/config.properties");
		FileOutputStream fileOut;
		try {
			fileOut = new FileOutputStream(file);
			installProperties.store(fileOut, "This is an autogenerated file for dclient");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
